Rscript   3-fit_motif.R    --motif=AAAAA   --rcmotif=TTTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAAC   --rcmotif=GTTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAAG   --rcmotif=CTTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAAT   --rcmotif=ATTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAACA   --rcmotif=TGTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAACC   --rcmotif=GGTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAACG   --rcmotif=CGTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAACT   --rcmotif=AGTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAGA   --rcmotif=TCTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAGC   --rcmotif=GCTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAGG   --rcmotif=CCTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAAGT   --rcmotif=ACTTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAATA   --rcmotif=TATTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAATC   --rcmotif=GATTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAATG   --rcmotif=CATTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AAATT   --rcmotif=AATTT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAAA   --rcmotif=TTTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAAC   --rcmotif=GTTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAAG   --rcmotif=CTTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAAT   --rcmotif=ATTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACACA   --rcmotif=TGTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACACC   --rcmotif=GGTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACACG   --rcmotif=CGTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACACT   --rcmotif=AGTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAGA   --rcmotif=TCTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAGC   --rcmotif=GCTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAGG   --rcmotif=CCTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACAGT   --rcmotif=ACTGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACATA   --rcmotif=TATGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACATC   --rcmotif=GATGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACATG   --rcmotif=CATGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ACATT   --rcmotif=AATGT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAAA   --rcmotif=TTTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAAC   --rcmotif=GTTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAAG   --rcmotif=CTTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAAT   --rcmotif=ATTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGACA   --rcmotif=TGTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGACC   --rcmotif=GGTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGACG   --rcmotif=CGTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGACT   --rcmotif=AGTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAGA   --rcmotif=TCTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAGC   --rcmotif=GCTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAGG   --rcmotif=CCTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGAGT   --rcmotif=ACTCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGATA   --rcmotif=TATCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGATC   --rcmotif=GATCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGATG   --rcmotif=CATCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=AGATT   --rcmotif=AATCT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAAA   --rcmotif=TTTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAAC   --rcmotif=GTTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAAG   --rcmotif=CTTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAAT   --rcmotif=ATTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATACA   --rcmotif=TGTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATACC   --rcmotif=GGTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATACG   --rcmotif=CGTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATACT   --rcmotif=AGTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAGA   --rcmotif=TCTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAGC   --rcmotif=GCTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAGG   --rcmotif=CCTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATAGT   --rcmotif=ACTAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATATA   --rcmotif=TATAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATATC   --rcmotif=GATAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATATG   --rcmotif=CATAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=ATATT   --rcmotif=AATAT   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAAA   --rcmotif=TTTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAAC   --rcmotif=GTTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAAG   --rcmotif=CTTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAAT   --rcmotif=ATTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAACA   --rcmotif=TGTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAACC   --rcmotif=GGTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAACG   --rcmotif=CGTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAACT   --rcmotif=AGTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAGA   --rcmotif=TCTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAGC   --rcmotif=GCTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAGG   --rcmotif=CCTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAAGT   --rcmotif=ACTTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAATA   --rcmotif=TATTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAATC   --rcmotif=GATTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAATG   --rcmotif=CATTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CAATT   --rcmotif=AATTG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAAA   --rcmotif=TTTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAAC   --rcmotif=GTTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAAG   --rcmotif=CTTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAAT   --rcmotif=ATTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCACA   --rcmotif=TGTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCACC   --rcmotif=GGTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCACG   --rcmotif=CGTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCACT   --rcmotif=AGTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAGA   --rcmotif=TCTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAGC   --rcmotif=GCTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAGG   --rcmotif=CCTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCAGT   --rcmotif=ACTGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCATA   --rcmotif=TATGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCATC   --rcmotif=GATGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCATG   --rcmotif=CATGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CCATT   --rcmotif=AATGG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAAA   --rcmotif=TTTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAAC   --rcmotif=GTTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAAG   --rcmotif=CTTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAAT   --rcmotif=ATTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGACA   --rcmotif=TGTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGACC   --rcmotif=GGTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGACG   --rcmotif=CGTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGACT   --rcmotif=AGTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAGA   --rcmotif=TCTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAGC   --rcmotif=GCTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAGG   --rcmotif=CCTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGAGT   --rcmotif=ACTCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGATA   --rcmotif=TATCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGATC   --rcmotif=GATCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGATG   --rcmotif=CATCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CGATT   --rcmotif=AATCG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAAA   --rcmotif=TTTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAAC   --rcmotif=GTTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAAG   --rcmotif=CTTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAAT   --rcmotif=ATTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTACA   --rcmotif=TGTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTACC   --rcmotif=GGTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTACG   --rcmotif=CGTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTACT   --rcmotif=AGTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAGA   --rcmotif=TCTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAGC   --rcmotif=GCTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAGG   --rcmotif=CCTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTAGT   --rcmotif=ACTAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTATA   --rcmotif=TATAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTATC   --rcmotif=GATAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTATG   --rcmotif=CATAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=CTATT   --rcmotif=AATAG   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAAA   --rcmotif=TTTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAAC   --rcmotif=GTTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAAG   --rcmotif=CTTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAAT   --rcmotif=ATTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAACA   --rcmotif=TGTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAACC   --rcmotif=GGTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAACG   --rcmotif=CGTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAACT   --rcmotif=AGTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAGA   --rcmotif=TCTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAGC   --rcmotif=GCTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAGG   --rcmotif=CCTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAAGT   --rcmotif=ACTTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAATA   --rcmotif=TATTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAATC   --rcmotif=GATTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAATG   --rcmotif=CATTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GAATT   --rcmotif=AATTC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAAA   --rcmotif=TTTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAAC   --rcmotif=GTTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAAG   --rcmotif=CTTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAAT   --rcmotif=ATTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCACA   --rcmotif=TGTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCACC   --rcmotif=GGTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCACG   --rcmotif=CGTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCACT   --rcmotif=AGTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAGA   --rcmotif=TCTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAGC   --rcmotif=GCTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAGG   --rcmotif=CCTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCAGT   --rcmotif=ACTGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCATA   --rcmotif=TATGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCATC   --rcmotif=GATGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCATG   --rcmotif=CATGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GCATT   --rcmotif=AATGC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAAA   --rcmotif=TTTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAAC   --rcmotif=GTTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAAG   --rcmotif=CTTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAAT   --rcmotif=ATTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGACA   --rcmotif=TGTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGACC   --rcmotif=GGTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGACG   --rcmotif=CGTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGACT   --rcmotif=AGTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAGA   --rcmotif=TCTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAGC   --rcmotif=GCTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAGG   --rcmotif=CCTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGAGT   --rcmotif=ACTCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGATA   --rcmotif=TATCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGATC   --rcmotif=GATCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGATG   --rcmotif=CATCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GGATT   --rcmotif=AATCC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAAA   --rcmotif=TTTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAAC   --rcmotif=GTTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAAG   --rcmotif=CTTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAAT   --rcmotif=ATTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTACA   --rcmotif=TGTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTACC   --rcmotif=GGTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTACG   --rcmotif=CGTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTACT   --rcmotif=AGTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAGA   --rcmotif=TCTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAGC   --rcmotif=GCTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAGG   --rcmotif=CCTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTAGT   --rcmotif=ACTAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTATA   --rcmotif=TATAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTATC   --rcmotif=GATAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTATG   --rcmotif=CATAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=GTATT   --rcmotif=AATAC   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAAA   --rcmotif=TTTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAAC   --rcmotif=GTTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAAG   --rcmotif=CTTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAAT   --rcmotif=ATTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAACA   --rcmotif=TGTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAACC   --rcmotif=GGTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAACG   --rcmotif=CGTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAACT   --rcmotif=AGTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAGA   --rcmotif=TCTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAGC   --rcmotif=GCTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAGG   --rcmotif=CCTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAAGT   --rcmotif=ACTTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAATA   --rcmotif=TATTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAATC   --rcmotif=GATTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAATG   --rcmotif=CATTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TAATT   --rcmotif=AATTA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAAA   --rcmotif=TTTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAAC   --rcmotif=GTTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAAG   --rcmotif=CTTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAAT   --rcmotif=ATTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCACA   --rcmotif=TGTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCACC   --rcmotif=GGTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCACG   --rcmotif=CGTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCACT   --rcmotif=AGTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAGA   --rcmotif=TCTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAGC   --rcmotif=GCTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAGG   --rcmotif=CCTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCAGT   --rcmotif=ACTGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCATA   --rcmotif=TATGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCATC   --rcmotif=GATGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCATG   --rcmotif=CATGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TCATT   --rcmotif=AATGA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAAA   --rcmotif=TTTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAAC   --rcmotif=GTTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAAG   --rcmotif=CTTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAAT   --rcmotif=ATTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGACA   --rcmotif=TGTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGACC   --rcmotif=GGTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGACG   --rcmotif=CGTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGACT   --rcmotif=AGTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAGA   --rcmotif=TCTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAGC   --rcmotif=GCTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAGG   --rcmotif=CCTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGAGT   --rcmotif=ACTCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGATA   --rcmotif=TATCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGATC   --rcmotif=GATCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGATG   --rcmotif=CATCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TGATT   --rcmotif=AATCA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAAA   --rcmotif=TTTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAAC   --rcmotif=GTTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAAG   --rcmotif=CTTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAAT   --rcmotif=ATTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTACA   --rcmotif=TGTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTACC   --rcmotif=GGTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTACG   --rcmotif=CGTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTACT   --rcmotif=AGTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAGA   --rcmotif=TCTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAGC   --rcmotif=GCTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAGG   --rcmotif=CCTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTAGT   --rcmotif=ACTAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTATA   --rcmotif=TATAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTATC   --rcmotif=GATAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTATG   --rcmotif=CATAA   --outDir=3-fit
Rscript   3-fit_motif.R    --motif=TTATT   --rcmotif=AATAA   --outDir=3-fit
